using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AQACommute.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AJAXControllerTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AJAXControllerTest()
        {
            this.CommuteLocations = new HashSet<CommuteLocation>();
        }

        public int CommuteID { get; set; }
        public string CommuteTime { get; set; }
        public string StartPoint { get; set; }
        public string EndPoint { get; set; }
        public Nullable<double> TotalMiles { get; set; }
        public double CO2GeneratedLbs { get; set; }
        public int TransportMethodID { get; set; }

        public virtual TransportMethod TransportMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommuteLocation> CommuteLocations { get; set; }
    }
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
}

