//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQACommute.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AQACommuteDBEntities : DbContext
    {
        public AQACommuteDBEntities()
            : base("name=AQACommuteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commute> Commutes { get; set; }
        public virtual DbSet<CommuteLocation> CommuteLocations { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<TransportMethod> TransportMethods { get; set; }
        public virtual DbSet<UTM> UTMs { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
