//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQACommute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commute
    {
        public int CommuteID { get; set; }
        public double DistanceTraveled { get; set; }
        public Nullable<System.DateTime> CommuteTimeSpent { get; set; }
        public Nullable<System.DateTime> CommuteTimeEnd { get; set; }
        public double C02Footprint { get; set; }
        public Nullable<int> VehicleID { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }

    }
}
