//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQACommute.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TransportMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportMethod()
        {
            this.Commutes = new HashSet<Commute>();
            this.UTMs = new HashSet<UTM>();
        }
    
        [Display(Name = "Transport Method")]
        public int TransportMethodID { get; set; }
        public string TransportMode { get; set; }

        [Display(Name = "Transport Class")]
        public string TransportClass { get; set; }

        [Display(Name = "AVG MPG")]
        public double AvgMPG { get; set; }

        [Display(Name = "City MPG")]
        public Nullable<double> CityMPG { get; set; }

        [Display(Name = "HWY MPG")]
        public Nullable<double> HwyMPG { get; set; }

        [Display(Name = "CO2 Lbs")]
        public Nullable<double> CO2Lbs { get; set; }

        public Nullable<int> MakeID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> OptionID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string Options { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commute> Commutes { get; set; }
        public virtual Make Make1 { get; set; }
        public virtual Model Model1 { get; set; }
        public virtual Option Option { get; set; }
        public virtual Year Year1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTM> UTMs { get; set; }
    }
}
