// <auto-generated />
namespace AQACommute.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CommuteID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommuteID));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041702439_CommuteID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
